### ISSUE TITLE
Tax demo setup.py error: config.yaml missing 'docai_active_processors` attribute

### ISSUE THREAD

**Issue by matthewayne** [GoogleCloudPlatform/document-ai-samples#107]
### Summary

running `python setup.py` fails the first time because `consts.py` (which is imported by `setup.py`) expects a `docai_active_processors` attribute in `config.yaml` that is not present. 

Recommended fixes: either remove the need for `docai_active_processors` in `config.yaml` for the first time its run on add the `docai_active_processors` attribute to `config.yaml`.

### Steps to reproduce:
1. Install deps `pip install -r requirements.txt`
1. setup a GCP project and add the project ID in the two places in `config.yaml`
1. enable the API `gcloud services enable documentai.googleapis.com`
1. setup ADC: `gcloud auth application-default login`
1. run `python3 setup.py`

### Expected result

`setup.py` to run without error and setup the repo correctly.

### Actual result

```
$ python setup.py
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    from consts import (
  File "consts.py", line 106, in <module>
    DOCAI_ACTIVE_PROCESSORS = CONFIG["docai_active_processors"]
KeyError: 'docai_active_processors'
```

### Other notes

I fixed the issue by adding `docai_active_processors:` to the end of the `config.yaml` file:
```
docai_processor_location: us
docai_project_id: [redacted]
firestore:
  collection: tax_demo_documents
  project_id: [redacted]
docai_active_processors:
```

After running setup.py the `docai_active_processors:` was full of processor names so I think its working after my fix:
```
docai_active_processors:
  FORM_1099DIV_PROCESSOR: 86dd76208ceee1de
  FORM_1099INT_PROCESSOR: d1caca1f2b0921ef
  FORM_1099MISC_PROCESSOR: 86dd76208ceee728
  FORM_1099NEC_PROCESSOR: 7e064b26498d9c8b
  FORM_PARSER_PROCESSOR: bf962e82d1afb5a9
  FORM_W2_PROCESSOR: 7e064b26498d9a03
  LENDING_DOCUMENT_SPLIT_PROCESSOR: 95e9f55d8b2a23f0
docai_processor_location: us
docai_project_id: [redacted]
firestore:
  collection: tax_demo_documents
  project_id: [redacted]
```
